name: Deploy Flask App to Azure

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.5"  # Specify your Terraform version

      - name: Terraform Initialize
        run: terraform init
        working-directory: ./terraform  # Adjust based on your Terraform files' location

      - name: Terraform Apply
        run: |
          terraform apply -input=false -auto-approve
        working-directory: ./terraform
        env:
          TF_VAR_acr_username: ${{ secrets.ACR_USERNAME }}
          TF_VAR_acr_password: ${{ secrets.ACR_PASSWORD }}
          TF_VAR_AZURE_EMAIL_CONNECTION_STRING: ${{ secrets.AZURE_MAIL_CONNECTION_STRING }}
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

      - name: Archive Terraform state file
        uses: actions/upload-artifact@v3
        with:
          name: terraform-state
          path: terraform/terraform.tfstate
