name: Wait 5 Minutes

on: workflow_dispatch

jobs:
  wait:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download Terraform state file
        uses: actions/download-artifact@v4
        with:
          name: terraform-state
          path: terraform/
        
      - name: Wait 5 minutes
        uses: jakejarvis/wait-action@master
        with:
          time: '5m'
          
      - name: Archive Terraform state file
        uses: actions/upload-artifact@v3
        with:
          name: terraform-state
          path: terraform/terraform.tfstate
